version: '3.8'

services:
    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0 --default-authentication-plugin=mysql_native_password
        container_name: db
        restart: always
        tty: true
        volumes: 
            - ./mysql:/var/lib/mysql
            - ./log:/var/log
            
        environment: 
            - MYSQL_DATABASE=vadetaxi
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "3306:3306"    